[package]
name = "diiudicatio"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
